### ISSUE TITLE
Rajouter le lien de téléchargement sous chaque vidéos

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#178]
Peut-être ce bug est-il lié à l'absence d'import ? Pas certain qu'il faille changer qu'il y est quelque chose à faire du coup..

**Comment by DavidRobertAnsart** [comment]
Puis-je avoir un lien vers une activité qui n'a pas ce bouton de téléchargement de vidéo?

**Comment by cecilelvq** [comment]
https://1v-staging.parlemonde.org/creer-un-jeu/mimique/jouer 

Dans le VM Palestine Sri Lanka
