### ISSUE TITLE
Bug import vidéo prof 1Village prod

### ISSUE THREAD

**Issue by cecilelvq** [parlemonde/1village#187]
Salut @DavidRobertAnsar

Il y a un bug sur 1Village sur le site de prod. 

Je me suis connectée comme une enseignante "Ileana Mirela Secu Iancu" et lorsque je souhaite insérer une vidéo de type .mov voici le message d'erreur qui s'affiche. Le même message d'erreur s'affiche avec une vidéo .mp4

https://user-images.githubusercontent.com/95769470/145252880-a6e422a6-6aad-44c2-8f1b-b75bbf129e45.mp4

**Comment by DavidRobertAnsart** [comment]
C'était peut-être du à un problème de fichier vidéo trop lourd pour être uploadé. J'ai augmenté sur le serveur les tailles limites. Pouvez-vous réessayer et me dire si le problème est corrigé ou non?

**Comment by cecilelvq** [comment]
Malheureusement le bug persiste... 

https://user-images.githubusercontent.com/95769470/148770468-c05b2574-ad03-4b61-9d63-9213b2eb2f9c.mov

**Comment by DavidRobertAnsart** [comment]
Même chose, je n'arrive pas à reproduire le bug, je peux uploader sans problème des vidéos `.mov` ou `.mp4`...

J'ai besoin aussi de plus d'informations:
- Est-ce lié à un utilisateur en particulier ? Ou ce bug est-il présent pour toutes les classes ?
- Quel navigateur est utilisé ? (avec version ?)
- Puis-je avoir une vidéo qui génère le bug ?

**Comment by cecilelvq** [comment]
Je te mets le lien Viméo parce que c’est trop lourd pour être importé ici : https://vimeo.com/pelicoplm/download/662211981/a96e5862e9

**Comment by DavidRobertAnsart** [comment]
Merci ! Erreur trouvée et normalement corrigée !! Pouvez vous me le confirmer ?

**Comment by cecilelvq** [comment]
Yes c’est parfait ! Merci beaucoup
