### ISSUE TITLE
Bug lors de l’import de photos mascotte 1Village

### ISSUE THREAD

**Issue by cecilelvq** [parlemonde/1village#189]
@DavidRobertAnsart 

Il y a un bug lors de l’import d’une photo à l’étape 1 de la mascotte « À quoi ressemble votre classe ? » > « Image de votre affiche ou décoration ». Une erreur s’affiche lorsqu’on souhaite insérer une image enregistrée sur l’ordinateur. 

Dans la vidéo je suis connectée comme une enseignante « Annabelle Pouille ». Je souhaite insérer une image de type . JPG

https://user-images.githubusercontent.com/95769470/145578020-161072b3-b8ab-410b-92ee-99b0305eb85d.mov

Ce bug ne concerne pas l’import d’image avec une URL

**Comment by DavidRobertAnsart** [comment]
Je suppose que c'était du à un problème d'image trop lourde pour être uploadé. J'ai augmenté sur le serveur les tailles limites. Pouvez-vous réessayer et me dire si le problème est corrigé ou non?

**Comment by cecilelvq** [comment]
Le bug persiste

https://user-images.githubusercontent.com/95769470/148771351-129ef1f3-e137-42fe-a2b2-e7e2443917db.mov

**Comment by DavidRobertAnsart** [comment]
Je n'arrive pas à reproduire l'erreur... J'ai besoin de plus d'informations:
- Est-ce lié à un utilisateur en particulier ? Ou ce bug est-il présent pour toutes les classes ?
- Quel navigateur est utilisé ? (avec version ?)
- Puis-je avoir une image qui génère le bug ?

**Comment by DavidRobertAnsart** [comment]
Merci ! Erreur trouvée et normalement corrigée !! Pouvez vous me le confirmer ?

**Comment by cecilelvq** [comment]
Bravo, ça fonctionne ! Merci :)
