### ISSUE TITLE
Photo qui pivote en fonction du logiciel d’ouverture

### ISSUE THREAD

**Issue by cecilelvq** [parlemonde/1village#190]
@DavidRobertAnsart 

Je ne sais pas si c’est un bug lié à 1Village ou aux méta-données de l’image en question. 

Pour te donner le contexte, une enseignante « Gabriela Miron »  souhaite insérer une image de son sapin dans la première étape de la mascotte.
Mais sa photo s’insère en pivotant automatiquement sur le côté. Je lui ai demandé de me l’envoyer pour faire des tests. Mais en fonction du logiciel/ de l’ordinateur utilisé la photo ne s’affiche pas dans le même sens. 

Voici mes tests en vidéo 
[Photo qui pivote sur 1V.mov.zip](https://github.com/parlemonde/1village/files/7692975/Photo.qui.pivote.sur.1V.mov.zip)

Et voici la photo en question 
![20211207_142628](https://user-images.githubusercontent.com/95769470/145580168-a23c2aa7-f2e9-492e-b0ef-cd391be7ccba.jpg)

Merci :)

**Comment by DavidRobertAnsart** [comment]
Les données `metadata` de l'image étaient effectivement perdu lors de l'upload. J'ai corrigé le problème et les images vont maintenant bien garder leur orientation originales.
