### ISSUE TITLE
Wording + disposition carte résumée

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#234]
Dans le titre de la carte "A réaliser -> a réalisé"

Le bouton contenant le nombre de commentaires n'est pas aligné avec le bouton "voir le reportage"
![image](https://user-images.githubusercontent.com/20889221/149320693-9cfdbac1-3ffd-404b-8c4e-99dff30113ef.png)

**Comment by DavidRobertAnsart** [comment]
Corrigé !
