### ISSUE TITLE
Droit des comptes observateurs

### ISSUE THREAD

**Issue by cecilelvq** [parlemonde/1village#264]
Les comptes observateurs peuvent pour le moment sur le site de prob publier du contenu. 

Il faudrait restreindre leur droit pour qu'ils puissent voir toutes les étapes de création d'une activité mais que le bouton "publier" reste toujours grisé même en ayant rempli toutes les catégories de l'activité. 

Empêcher également les réactions et les commentaires sous les activités

**Comment by yudino** [comment]
Comment and reaction are missing in the previous PR
