### ISSUE TITLE
Jouer accessible à une classe qui n'a pas partagé de mimique

### ISSUE THREAD

**Issue by cecilelvq** [parlemonde/1village#276]
Dans cet exemple, on voit que je suis connectée comme une classe qui ne s'est jamais connecté à 1Village (c'est donc sur qu'elle n'a jamais créé de mimique) et elle peut "découvrir les mimiques" avec qu'elle n'en a pas partagé. 

Restreindre la découverte des mimiques aux classes qui ont créé des mimiques 

https://user-images.githubusercontent.com/95769470/154500164-16b8ffb2-b39b-4b70-9d2c-6da1c10cfaf2.mov

**Comment by larnoult** [comment]
Bug toujours identique à celui remonté par @cecilelvq !
