### ISSUE TITLE
Rendre clicable l'image à la une du feed

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#303]
Lorsqu'une activité dans le feed possède une image à la une, il serait plus agréable de pouvoir cliquer dessus pour se rendre sur le détail de l'activité.
![image](https://user-images.githubusercontent.com/20889221/157205028-4fd63d70-f73c-40c1-9d3f-2e29af3ba62f.png)

**Comment by larnoult** [comment]
Fonctionne sur staging. Par contre, le curseur n'indique pas qu'il y a un lien pour toutes les images. Par ex, pour cette activité du VM France-Maroc, il est sous forme de flèche plutôt que de main.
![image](https://user-images.githubusercontent.com/20889221/158209987-5960c09c-60e4-41cb-81a2-89fd4a0aa1a9.png)

**Comment by larnoult** [comment]
Le lien entre l'image à la une et l'activité est toujours actif dans l'écran "réagir à une activité".. Il ne devrait pas.

**Comment by yudino** [comment]
@larnoult Le correctif pour les images des Cards dans l'activité Réagir est disponible sur staging.
