### ISSUE TITLE
Rendre cliquable les mascottes partout sur 1Village

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#304]
Actuellement, il n'est pas clair quand l'image d'une mascotte dirige ou non vers la page mascotte. 
Je propose de simplifier en ajoutant un lien vers la page de la mascotte partout où elle s'affiche, notamment : 
- depuis la carte du monde 
- depuis le widget latéral contextuel 
![image](https://user-images.githubusercontent.com/20889221/157222751-486cdcec-a480-4fc6-8d19-5c8e2855ff73.png)

Ajout d'un lien vers la mascotte depuis la carte
Actuellement, des informations apparraisent en passant la souris par dessus l'icone. En cliquant, on aimerait que les classes puissent accéder à la page de visualisation de la mascotte.
Cette fonctionnalité rejoint l'issue https://github.com/parlemonde/1village/issues/304 dans son esprit

![image](https://user-images.githubusercontent.com/61083815/191943592-98ef07a2-8750-414a-8aae-0b2631fb1a43.png)

**Comment by larnoult** [comment]
Cela fonctionne bien, modulo une amélioration à apporter sur la carte, que je renseigne dans #414

**Comment by larnoult** [comment]
Cela fonctionne bien, modulo une amélioration à apporter sur la carte, que je renseigne dans #414

**Comment by yudino** [comment]
> @larnoult Pour le cursur not-allowed, la fonction est disponible sur staging et fonctionne bien en local : ![IMG_20220929_093205](https://user-images.githubusercontent.com/75479164/192968859-52fbbe05-b3cd-4f93-9326-6764c9cf19ae.jpg) En attente de ton retour

**Comment by larnoult** [comment]
@yudino il y a une régression : en passant sur l'avatar des classes sans mascotte dans le fil d'activité (ou bien dans le header ou bien dans le menu contextuel de droite), on a perdu le style "not-allowed".

**Comment by yudino** [comment]
@larnoult J'ai (re)vérifié et le menu de droite fonctionnait bien chez moi par contre il manquait effectivement le correctif sur Avatar. Je viens de pousser sur staging la correction.
