### ISSUE TITLE
Faire évoluer la liste des langues

### ISSUE THREAD

**Issue by Houra-Am** [parlemonde/1village#306]
La langue de certaines classes ne s’affiche pas à l’auto-complétion. Par exemple, l’amazighe, un dialecte marocain. Pourtant elle est dans [1village/server/utils/iso-639-languages-french.ts](https://github.com/parlemonde/1village/blob/16b6ce4d810b566281a3c87855e17029759529c0/server/utils/iso-639-languages-french.ts)

![image](https://user-images.githubusercontent.com/61083815/157246064-f751ee45-6478-4772-b100-0a5d6bdd5df2.png)

**Comment by larnoult** [comment]
@Houra-Am as-tu mis à jour le fichier avec davantage de langues ou bien réparé un bug qui faisait que certaines langues du fichier ne s'affichait pas en autocomplétion ?

**Comment by Houra-Am** [comment]
@larnoult J'ai mis à jour le fichier iso-639-languages-french.ts. Comme Cécile me l'a dit, j'ai supprimé les options qui indiquaient un "groupe de langues" ou des langues qui ne sont plus parlées (image ci-dessous). Les langues auxquelles tu fais référence, veux-tu qu'elles soient affichées ou non ?

![image](https://user-images.githubusercontent.com/61083815/158338265-83c9e8ab-28e3-467d-be11-739326bc1312.png)
