### ISSUE TITLE
Changement de phase au rafraîchissement de la page

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#367]
Bug non présent sur la prod. Lorsqu'on rafraîchit la page, on repasse en phase 1. Cela prête particulièrement à confusion au milieu de la création de l'histoire.

https://user-images.githubusercontent.com/20889221/164780682-3bf6c4c9-5e65-412c-b6cb-f20a1e85d730.mov

**Comment by cecilelvq** [comment]
Le bug est désormais présent en prod
