### ISSUE TITLE
Bug lors de la ré-invention d'une histoire simple

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#390]
À l'étape 1 de l'objet magique, lorsque je te tente de supprimer la photo (hérité de l'histoire simple inspirante), j'obtiens une erreur en passant à l'écran suivant : 
<img width="1942" alt="image" src="https://user-images.githubusercontent.com/20889221/169788300-42df48e8-7977-4eaa-b8e4-53a2d979a470.png">

**Comment by yudino** [comment]
Normalement le bug devrait être réglé :
https://www.loom.com/share/eab4dc4558e24658b4eed810b6d698c5
