### ISSUE TITLE
Modification touchant à l'accessibilité des mascottes

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#414]
**Publications des mascottes dans la bonne phase** 
Actuellement, les classes du pays 1 ne peuvent pas consulter les mascottes des classes du pays 2 :-(
Ce comportement est peut-être lié au fait que la création de la mascotte est rattachée aux activités de la phase 1, alors qu'elle ne devrait pas (elle peut être créée à chaque phase du projet). 
Nous aimerions que toutes les classes puissent consulter toutes les mascottes en phase 2 et 3 (en phase 1, elles ne voient que celles de leurs pays).

**Comment by Houra-Am** [comment]
The map modification is in progress and will be treated in a separate issue.

**Comment by larnoult** [comment]
Impossible d'accéder aux pages des mascottes dans mes tests, sauf de la sienne. 
À discuter avec #304

**Comment by larnoult** [comment]
@Houra-Am Pour la carte 3D, cela fonctionne bien, mais ce n'est pas très intuitif car lorsqu'on passe sur la souris sur les classes qui n'ont pas encore de mascotte, le style de cursor est de type "pointer" alors que justement on ne peut que cliquer que sur les classes qui ont déjà fait leur mascotte. Comme dans le flux d'activité, pourriez-vous modifier le style du cursor pour les classes sans mascottes, et appliquer la valeur "not-allowed" ?

**Comment by larnoult** [comment]
Pour le changement dans l'accès aux mascottes, je valide. Au passage, je ne ferai plus ça ; j'aurais du publier deux issues.

**Comment by Houra-Am** [comment]
La deuxième partie de cette issue a été transférée à l'issue #304 afin de faciliter le suivi des commits et des changements de fichiers.

**Comment by yudino** [comment]
@larnoult Pour le cursur not-allowed, la fonction est disponible sur staging et fonctionne bien en local : 
![IMG_20220929_093205](https://user-images.githubusercontent.com/75479164/192968859-52fbbe05-b3cd-4f93-9326-6764c9cf19ae.jpg)
En attente de ton retour
