### ISSUE TITLE
Rajouter aux commentaires, date et drapeau (comme dans le header des activités).

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#415]
Actuellement, dans l'espace de réactions des Pélicopains, le commentaire n'affiche que le nom de la classe. On aimerait afficher également date de publication et drapeau (comme sous le header d'activité). 
![image](https://user-images.githubusercontent.com/20889221/180000203-2d98c745-0627-4a18-8149-160eea66aef2.png)
--> 
![image](https://user-images.githubusercontent.com/20889221/180000233-6b4eeefe-93f0-4c2f-b3df-837a535d6845.png)

**Comment by larnoult** [comment]
La date publiée sous le commentaire n'est pas bonne. Il s'agit de la date de publication de l'activité, et non celle du commentaire. Voir ce commentaire réalisé le 15 septembre.. et qui affiche la date du 2 décembre 
<img width="876" alt="image" src="https://user-images.githubusercontent.com/20889221/190344774-a612be2e-869c-4bbe-9f33-ee1db7cb61a3.png">

**Comment by yudino** [comment]
La correction est déployer sur staging (en local la modification fonctionne).

**Comment by larnoult** [comment]
Pour les commentaires laissés par Pelico, il ne faut pas afficher un drapeau français, mais l'icone de Pelico 
<img width="837" alt="image" src="https://user-images.githubusercontent.com/20889221/191935997-2f712d18-038f-4b90-aa99-590bbcda9b2c.png">
L'icone est celle présente dans le header du titre des activités publiées par Pelico : 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/20889221/191936051-779ebaba-2332-413d-a43d-00ae38a82ceb.png">

**Comment by yudino** [comment]
@larnoult J'ai déployé le correctif sur staging avec les autres issues en cours pour test
