### ISSUE TITLE
Modifier le menu actionel latéral

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#427]
[Voir la maquette](https://www.figma.com/proto/rTq6xr5BTPQBwVXtK2peK9/1V-2022-23?node-id=5136%3A73681&viewport=4220%2C3366%2C0.22&scaling=min-zoom&starting-point-node-id=5136%3A73685)

![Image](https://user-images.githubusercontent.com/20889221/190658222-7ed2633a-5e3b-4407-8721-76a5b89eb5f6.png)

Il faut : 

- enlever "poser une question" du menu 
- rajouter "créer sa mascotte" (qui est un raccourci vers /mascotte/1)
- changer l'icone de ma classe : par défaut, mettre la même icone aléatoire qui correspond à la classe connectée.

**Comment by larnoult** [comment]
Le raccourci pour créer sa mascotte depuis le menu conduit bien vers /mascotte/1 ... mais en fait, quand la classe a déjà créé sa mascotte, il serait plus logique de redirriger vers /mascotte/5 (l'écran de prévisualisation).

**Comment by larnoult** [comment]
Je ne suis pas d'accord avec votre choix d'icone pour "Notre classe" (générique gris). Je trouve ça mieux l'ancienne version générée aléatoirement, qui permettait de distinguer les classes, même sans mascotte. Par ailleurs, les anciennes icones sont sur le globe. 
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/20889221/191927810-4acd9852-b8be-48c3-9b4d-f1e1a903dbd0.png">
Pourriez-vous revenir à l'ancien modèle "mosaïque" ?

**Comment by yudino** [comment]
Pour la correction de l'avatar de la mascotte, elle est lié au la PR #421

**Comment by larnoult** [comment]
@yudino la correction de l'avatar de la mascotte fonctionne. 
Par contre, il reste encore à modifier le comportement du bouton raccourci "créer sa mascotte" tel que décrit dans le commentaire [plus-haut](https://github.com/parlemonde/1village/issues/427#issuecomment-1255964122).

**Comment by yudino** [comment]
@larnoult Justement la correction décrit ci-dessous fonctionne bien en locale : 

> Le raccourci pour créer sa mascotte depuis le menu conduit bien vers /mascotte/1 ... mais en fait, quand la classe a déjà créé sa mascotte ou qu'elle a déjà créé un brouillon, il serait plus logique de redirriger vers /mascotte/5 (l'écran de prévisualisation).

https://www.loom.com/share/c8db0a964e2d417daee829bed36be6df

**Comment by yudino** [comment]
@larnoult Oki je vois mais je pense c'est pas le même souci. Du coup, pour être sûr de bien comprendre pour un utilisateur qui a une mascotte, la modification fonctionne bien comme en locale mais pas dans le cas d'un brouillon ?

**Comment by larnoult** [comment]
@yudino Oui, pour un utilisateur qui a déjà créé sa mascotte, la redirection fonctionne. Par contre pour un utilisateur ayant commencé un brouillon de mascotte, cela renvoie toujours sur la première page (au lieu de renvoyer sur la page de prévi)

**Comment by yudino** [comment]
@larnoult Pour faire suite a ton retour sur la mascotte, le cas que tu décris est un cas particulier du coup. Parce ce que la manière dont le menu a été construit, les liens vont tous sur la page 1 de l'activité que l'utilisateur ait un brouillon ou non. Le comportement que tu veux se trouve déjà dans la section Ma Classe et Mes Brouillons qui redirige vers la page qu'on compléter en dernier. Du coup, tu veux mettre cette fonctionnalité dans le menu juste pour la mascotte ?

**Comment by yudino** [comment]
@larnoult Comme vu ensemble le comportement pour le menu latéral est calquer sur celui de ma classe. En attente de ton retour de la fonctionnalité sur staging
