### ISSUE TITLE
Modifier le comportement de la carte aperçu pour les classes sans mascotte

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#428]
Pour les classes sans mascotte, on ne peut pas cliquer sur l'icone générique, alors que pour les classes avec mascotte, on peut cliquer sur l'image et se rendre sur la page de la mascotte.
Pour faciliter la compréhension de ce comportement, je propose de rajouter un tooltip ("la classe n'a pas encore de mascotte") et de modifier la propriété cursor (not-allowed) quand l'utilisateur survole une icone générique d'une carte d'activité dans le flux de la phase 1, 2 et 3.

![Image](https://user-images.githubusercontent.com/20889221/190668059-46989cc2-5cc0-4d75-902d-e9628b29de44.png)

**Comment by yudino** [comment]
Issue already done in branch 304-rendre-cliquable-les-mascottes.
Wording will be change and cursor also
