### ISSUE TITLE
Modifier la liste des pays accessible depuis la création de mascotte

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#437]
Actuellement, il y a des ... régions d'outre-mer (cf Guadeloupe) ! Je ne sais pas d'où est tiré cette liste, mais je propose d'adopter celle de Wikipédia ; [les 197 États reconnus par l’Organisation des Nations unies.](https://fr.wikipedia.org/wiki/Liste_des_pays_du_monde#Liste_principale)  

![Image](https://user-images.githubusercontent.com/20889221/191928472-c1da12c3-ea5b-4500-8474-5a8fd5b23612.png)

**Comment by charlinedev** [comment]
@larnoult , concernant la liste des pays à modifier, est ce que tu souhaites simplement que je supprime les départements d'outre mer ? que je rajoute/supprime des états  en fonction de la liste des états de l'ONU ? 
La mascotte en à environ 245 actuellement, la liste de l'ONU en mentionne maintenant 197...
Si oui, est ce que quelqu'un sait d'où a été tiré ces 245 états / départements?

**Comment by larnoult** [comment]
@charlinedev Adoptons la liste des 197 états si c'est possible, pour éviter les maladresses comme "France" / "Guadeloupe"..

**Comment by larnoult** [comment]
@charlinedev quelle liste as-tu adopté ? Notamment, il y a le "Sahara Occidental" qui est un territoire disputé et non reconnu par le Maroc.. et qui ne fait pas partie de la liste des 197. Nous avons déjà eu beaucoup de souci avec ce territoire dans le passé.. peux-tu mettre à jour la liste ? 
<img width="944" alt="image" src="https://user-images.githubusercontent.com/20889221/194097241-6aea35c3-6343-49f0-9b1a-fe3bb61e8792.png">
Aussi, il y a une faute d'orthographe dans le texte d'erreur 
<img width="942" alt="image" src="https://user-images.githubusercontent.com/20889221/194097643-97a9f943-73a7-4406-9140-c7007ec6722a.png">
Pas de résultats ->> Pas de résultat
