### ISSUE TITLE
Modification de la vidéo d'accueil

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#441]
Changer la vidéo de la page d'accueil (qui s'affiche lorsqu'on n'est pas connecté) par celle-ci : https://vimeo.com/754287113

**Comment by yudino** [comment]
@larnoult Le lien ne fonctionne pas quand je clique dessus : 


![Image](https://user-images.githubusercontent.com/75479164/192730790-564c5951-e092-4caf-a68c-5e4d45f05447.png)
