### ISSUE TITLE
Empêcher Pelico de créer une mascotte

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#449]
Depuis la modification du menu latéral d'actions (#427), il est possible pour les médiateurs d'accéder à la création de la mascotte.. Ce que l'on ne veut pas. 
Pouvez-vous en interdire l'accès (et griser ou supprimer le bouton "créer sa mascotte") ?
Merci à @cecilelvq d'avoir repéré le bug 😄 

![Image](https://user-images.githubusercontent.com/20889221/193252126-2985ce25-da5e-4309-8954-8452ba805808.png)

**Comment by charlinedev** [comment]
@larnoult qui sont les médiateurs? Pélico est super admin, comme sur le screenshot. J'ai modifié les droits de médiator à l'identique d'observateur pour la mascotte c'est à dire qu'il ne peut pas publier la mascotte et qu'elle reste en brouillon, mais est ce vraiement cela l'objet de la request?

**Comment by larnoult** [comment]
Donc oui, pour répondre à ta question, il faut que tout compte dont les droits sont supérieurs à médiator (admin, super admin) et donc qui sont Pelico sur la plateforme aient les mêmes droits que les observateurs en ce qui concerne la création de la mascotte.
