### ISSUE TITLE
UPDT Défi libre

### ISSUE THREAD

**Issue by yudino** [parlemonde/1village#475]

**Comment by yudino** [comment]
#484 
@larnoult J'ai mis sur staging la branche pour testing pour le défi libre. De mon côté, tout fonctionne en local et sur staging de test de Sciam.

**Comment by larnoult** [comment]
@yudino whaoo ! Quelle rapidité !! Testé et approuvé sans bug 👍

**Comment by yudino** [comment]
@larnoult top parfait :)
