### ISSUE TITLE
Bug dans la publication de plusieurs questions

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#496]
Lorsqu'un utilisateur rentre deux ou trois questions, seule la 1ère se retrouve publiée sur le fil d'activité. 3 activités différentes, correspondant aux 3 questions, devraient être publiées.

**Comment by yudino** [comment]
@larnoult Je viens de faire une correction pour le bug des questions que j'ai push en staging. Pour information, ce n'est pas une régression car la fonctionnalité existait déjà et implémenté par David mais elle ne pouvait pas fonctionner avec la condition mise en place dans la page 3.

Ci-dessous un extrait du test en local : 
https://www.loom.com/share/d0120fb6c8a14aeebd1c8e98dd82cfa8

**Comment by larnoult** [comment]
Super, bonne nouvelle ! J'ai testé. Il serait sympa de griser le bouton "Ajouter une autre question" lorsqu'on a déjà listé 3 questions.
