### ISSUE TITLE
Erreur d'affichage à l'étape 3

### ISSUE THREAD

**Issue by geekplm** [parlemonde/1village#517]
À l'étape 3 s'affiche toujours le même texte "Expliquez pourquoi vous avez choisi ce mot précieux, ce qu’il signifie et quand vous l’utilisez", quel que soit le choix fait à l'étape 2. Dans cet exemple, la classe a choisi "Une chanson", le texte devrait afficher "Expliquez pourquoi vous avez choisi cette chanson, ce qu’elle signifie et quand vous l’utilisez". Même chose pour les autres aspects sélectionables en étape 2. 

![Image](https://user-images.githubusercontent.com/47036266/214576927-79a655b9-f7e9-4f27-a2c6-b24bc50b7976.png)

**Comment by yudino** [comment]
@geekplm C'est corrigé
