### ISSUE TITLE
Mettre l'icone corbeille à droite

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#552]
C'est plus logique par rapport aux autres éléments d'interface d'1Village (et c'était à droite dans la maquette 😇)

**Comment by charlinedev** [comment]
En teme d'UX on trouvait ca plus pratique pour supprimer, en fonction de la longueur de noms... Voilà ce que ca donne aligné à droite



![Image](https://user-images.githubusercontent.com/79838535/221208533-82d8e212-66b6-46d5-848b-6349a92ea0b3.jpg)
