### ISSUE TITLE
Le bouton "imprimer"... n'imprime pas

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#553]
Actuellement, cliquer sur ce bouton, cela ouvre un nouvel onglet avec le bon texte, mais ça n'ouvre pas la boite d'impression. 

https://user-images.githubusercontent.com/20889221/220960367-5d80978a-0441-419b-b3b8-c197992ac088.mp4

**Comment by YanLabarthe** [comment]
Bien plus difficile que prévu mais résolu (sur staging quand je test moi) !!
