### ISSUE TITLE
Empêcher la création d'un deuxième compte avec la même adresse mail

### ISSUE THREAD

**Issue by larnoult** [parlemonde/1village#556]
Pour l'instant c'est possible. Il faudrait afficher une erreur au moment de la soumission du formulaire de création : 
"un compte associé à cette adresse email existe déjà. Cliquez ici pour réinitialiser votre mot de passe".

**Comment by yudino** [comment]
@larnoult Pourrais-tu nous faire un loom sur cette erreur car en principe ce n'est pas possible avec la bdd actuelle.
