### ISSUE TITLE
Bug affichage réponses mimiques 

### ISSUE THREAD

**Issue by geekplm** [parlemonde/1village#784]
Hello ! 

Connectée en tant que classe, je joue à ma propre mimique et les chevrons de réponses ne s'adaptent pas à la taille du texte (voir capture) 

<img width="1043" alt="image" src="https://github.com/parlemonde/1village/assets/47036266/e1c5e2af-c279-48f4-b0f0-29fd087302e4">

**Comment by geekplm** [comment]
Suite du même bug, l'affichage des stats de réponses ne sont pas alignées avec les réponses choisies

<img width="1429" alt="image" src="https://github.com/parlemonde/1village/assets/47036266/583d8f20-ff34-422b-9752-c28163f98dd9">

**Comment by MarineChillaud** [comment]
@DavidRobertAnsart  je vais avoir besoin de toi là dessus. Tout fonctionne parfaitement en local, je ne trouve pas d'ou vient la différence
